// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/review_admin_service.proto

package admin

import (
	domain "github.com/martketplace-vkr/review/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReviewDisputesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewDisputesRequest) Reset() {
	*x = ListReviewDisputesRequest{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewDisputesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewDisputesRequest) ProtoMessage() {}

func (x *ListReviewDisputesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewDisputesRequest.ProtoReflect.Descriptor instead.
func (*ListReviewDisputesRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListReviewDisputesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListReviewDisputesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*domain.Review       `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewDisputesResponse) Reset() {
	*x = ListReviewDisputesResponse{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewDisputesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewDisputesResponse) ProtoMessage() {}

func (x *ListReviewDisputesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewDisputesResponse.ProtoReflect.Descriptor instead.
func (*ListReviewDisputesResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListReviewDisputesResponse) GetReviews() []*domain.Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type ListReviewReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewReportsRequest) Reset() {
	*x = ListReviewReportsRequest{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewReportsRequest) ProtoMessage() {}

func (x *ListReviewReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewReportsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListReviewReportsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReportedReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *domain.Review         `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	Report        *domain.ReviewReport   `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportedReview) Reset() {
	*x = ReportedReview{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportedReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportedReview) ProtoMessage() {}

func (x *ReportedReview) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportedReview.ProtoReflect.Descriptor instead.
func (*ReportedReview) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReportedReview) GetReview() *domain.Review {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *ReportedReview) GetReport() *domain.ReviewReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ListReviewReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReportedReview      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewReportsResponse) Reset() {
	*x = ListReviewReportsResponse{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewReportsResponse) ProtoMessage() {}

func (x *ListReviewReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewReportsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListReviewReportsResponse) GetItems() []*ReportedReview {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResolveReviewDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	DisputeId     int64                  `protobuf:"varint,3,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReviewDisputeRequest) Reset() {
	*x = ResolveReviewDisputeRequest{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReviewDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReviewDisputeRequest) ProtoMessage() {}

func (x *ResolveReviewDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReviewDisputeRequest.ProtoReflect.Descriptor instead.
func (*ResolveReviewDisputeRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveReviewDisputeRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *ResolveReviewDisputeRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ResolveReviewDisputeRequest) GetDisputeId() int64 {
	if x != nil {
		return x.DisputeId
	}
	return 0
}

func (x *ResolveReviewDisputeRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResolveReviewDisputeRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ResolveReviewDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *domain.Review         `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveReviewDisputeResponse) Reset() {
	*x = ResolveReviewDisputeResponse{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReviewDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReviewDisputeResponse) ProtoMessage() {}

func (x *ResolveReviewDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReviewDisputeResponse.ProtoReflect.Descriptor instead.
func (*ResolveReviewDisputeResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveReviewDisputeResponse) GetReview() *domain.Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       int64                  `protobuf:"varint,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReviewRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *DeleteReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_review_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_review_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteReviewResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_v1_admin_review_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_review_admin_service_proto_rawDesc = "" +
	"\n" +
	"#v1/admin/review_admin_service.proto\x12 martketplace.vkr.review.v1.admin\x1a\x1dv1/domain/review_domain.proto\"3\n" +
	"\x19ListReviewDisputesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"a\n" +
	"\x1aListReviewDisputesResponse\x12C\n" +
	"\areviews\x18\x01 \x03(\v2).martketplace.vkr.review.v1.domain.ReviewR\areviews\"2\n" +
	"\x18ListReviewReportsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x9c\x01\n" +
	"\x0eReportedReview\x12A\n" +
	"\x06review\x18\x01 \x01(\v2).martketplace.vkr.review.v1.domain.ReviewR\x06review\x12G\n" +
	"\x06report\x18\x02 \x01(\v2/.martketplace.vkr.review.v1.domain.ReviewReportR\x06report\"c\n" +
	"\x19ListReviewReportsResponse\x12F\n" +
	"\x05items\x18\x01 \x03(\v20.martketplace.vkr.review.v1.admin.ReportedReviewR\x05items\"\xaa\x01\n" +
	"\x1bResolveReviewDisputeRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x03 \x01(\x03R\tdisputeId\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"a\n" +
	"\x1cResolveReviewDisputeResponse\x12A\n" +
	"\x06review\x18\x01 \x01(\v2).martketplace.vkr.review.v1.domain.ReviewR\x06review\"M\n" +
	"\x13DeleteReviewRequest\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\x03R\aadminId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xcc\x04\n" +
	"\x12ReviewAdminService\x12\x8f\x01\n" +
	"\x12ListReviewDisputes\x12;.martketplace.vkr.review.v1.admin.ListReviewDisputesRequest\x1a<.martketplace.vkr.review.v1.admin.ListReviewDisputesResponse\x12\x8c\x01\n" +
	"\x11ListReviewReports\x12:.martketplace.vkr.review.v1.admin.ListReviewReportsRequest\x1a;.martketplace.vkr.review.v1.admin.ListReviewReportsResponse\x12\x95\x01\n" +
	"\x14ResolveReviewDispute\x12=.martketplace.vkr.review.v1.admin.ResolveReviewDisputeRequest\x1a>.martketplace.vkr.review.v1.admin.ResolveReviewDisputeResponse\x12}\n" +
	"\fDeleteReview\x125.martketplace.vkr.review.v1.admin.DeleteReviewRequest\x1a6.martketplace.vkr.review.v1.admin.DeleteReviewResponseB@Z>github.com/martketplace-vkr/review/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_review_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_review_admin_service_proto_rawDescData []byte
)

func file_v1_admin_review_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_review_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_review_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_review_admin_service_proto_rawDesc), len(file_v1_admin_review_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_review_admin_service_proto_rawDescData
}

var file_v1_admin_review_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_admin_review_admin_service_proto_goTypes = []any{
	(*ListReviewDisputesRequest)(nil),    // 0: martketplace.vkr.review.v1.admin.ListReviewDisputesRequest
	(*ListReviewDisputesResponse)(nil),   // 1: martketplace.vkr.review.v1.admin.ListReviewDisputesResponse
	(*ListReviewReportsRequest)(nil),     // 2: martketplace.vkr.review.v1.admin.ListReviewReportsRequest
	(*ReportedReview)(nil),               // 3: martketplace.vkr.review.v1.admin.ReportedReview
	(*ListReviewReportsResponse)(nil),    // 4: martketplace.vkr.review.v1.admin.ListReviewReportsResponse
	(*ResolveReviewDisputeRequest)(nil),  // 5: martketplace.vkr.review.v1.admin.ResolveReviewDisputeRequest
	(*ResolveReviewDisputeResponse)(nil), // 6: martketplace.vkr.review.v1.admin.ResolveReviewDisputeResponse
	(*DeleteReviewRequest)(nil),          // 7: martketplace.vkr.review.v1.admin.DeleteReviewRequest
	(*DeleteReviewResponse)(nil),         // 8: martketplace.vkr.review.v1.admin.DeleteReviewResponse
	(*domain.Review)(nil),                // 9: martketplace.vkr.review.v1.domain.Review
	(*domain.ReviewReport)(nil),          // 10: martketplace.vkr.review.v1.domain.ReviewReport
}
var file_v1_admin_review_admin_service_proto_depIdxs = []int32{
	9,  // 0: martketplace.vkr.review.v1.admin.ListReviewDisputesResponse.reviews:type_name -> martketplace.vkr.review.v1.domain.Review
	9,  // 1: martketplace.vkr.review.v1.admin.ReportedReview.review:type_name -> martketplace.vkr.review.v1.domain.Review
	10, // 2: martketplace.vkr.review.v1.admin.ReportedReview.report:type_name -> martketplace.vkr.review.v1.domain.ReviewReport
	3,  // 3: martketplace.vkr.review.v1.admin.ListReviewReportsResponse.items:type_name -> martketplace.vkr.review.v1.admin.ReportedReview
	9,  // 4: martketplace.vkr.review.v1.admin.ResolveReviewDisputeResponse.review:type_name -> martketplace.vkr.review.v1.domain.Review
	0,  // 5: martketplace.vkr.review.v1.admin.ReviewAdminService.ListReviewDisputes:input_type -> martketplace.vkr.review.v1.admin.ListReviewDisputesRequest
	2,  // 6: martketplace.vkr.review.v1.admin.ReviewAdminService.ListReviewReports:input_type -> martketplace.vkr.review.v1.admin.ListReviewReportsRequest
	5,  // 7: martketplace.vkr.review.v1.admin.ReviewAdminService.ResolveReviewDispute:input_type -> martketplace.vkr.review.v1.admin.ResolveReviewDisputeRequest
	7,  // 8: martketplace.vkr.review.v1.admin.ReviewAdminService.DeleteReview:input_type -> martketplace.vkr.review.v1.admin.DeleteReviewRequest
	1,  // 9: martketplace.vkr.review.v1.admin.ReviewAdminService.ListReviewDisputes:output_type -> martketplace.vkr.review.v1.admin.ListReviewDisputesResponse
	4,  // 10: martketplace.vkr.review.v1.admin.ReviewAdminService.ListReviewReports:output_type -> martketplace.vkr.review.v1.admin.ListReviewReportsResponse
	6,  // 11: martketplace.vkr.review.v1.admin.ReviewAdminService.ResolveReviewDispute:output_type -> martketplace.vkr.review.v1.admin.ResolveReviewDisputeResponse
	8,  // 12: martketplace.vkr.review.v1.admin.ReviewAdminService.DeleteReview:output_type -> martketplace.vkr.review.v1.admin.DeleteReviewResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_admin_review_admin_service_proto_init() }
func file_v1_admin_review_admin_service_proto_init() {
	if File_v1_admin_review_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_review_admin_service_proto_rawDesc), len(file_v1_admin_review_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_review_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_review_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_review_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_review_admin_service_proto = out.File
	file_v1_admin_review_admin_service_proto_goTypes = nil
	file_v1_admin_review_admin_service_proto_depIdxs = nil
}
