// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/admin/review_admin_service.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewAdminService_ListReviewDisputes_FullMethodName   = "/martketplace.vkr.review.v1.admin.ReviewAdminService/ListReviewDisputes"
	ReviewAdminService_ListReviewReports_FullMethodName    = "/martketplace.vkr.review.v1.admin.ReviewAdminService/ListReviewReports"
	ReviewAdminService_ResolveReviewDispute_FullMethodName = "/martketplace.vkr.review.v1.admin.ReviewAdminService/ResolveReviewDispute"
	ReviewAdminService_DeleteReview_FullMethodName         = "/martketplace.vkr.review.v1.admin.ReviewAdminService/DeleteReview"
)

// ReviewAdminServiceClient is the client API for ReviewAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewAdminServiceClient interface {
	ListReviewDisputes(ctx context.Context, in *ListReviewDisputesRequest, opts ...grpc.CallOption) (*ListReviewDisputesResponse, error)
	ListReviewReports(ctx context.Context, in *ListReviewReportsRequest, opts ...grpc.CallOption) (*ListReviewReportsResponse, error)
	ResolveReviewDispute(ctx context.Context, in *ResolveReviewDisputeRequest, opts ...grpc.CallOption) (*ResolveReviewDisputeResponse, error)
	DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error)
}

type reviewAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewAdminServiceClient(cc grpc.ClientConnInterface) ReviewAdminServiceClient {
	return &reviewAdminServiceClient{cc}
}

func (c *reviewAdminServiceClient) ListReviewDisputes(ctx context.Context, in *ListReviewDisputesRequest, opts ...grpc.CallOption) (*ListReviewDisputesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewDisputesResponse)
	err := c.cc.Invoke(ctx, ReviewAdminService_ListReviewDisputes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewAdminServiceClient) ListReviewReports(ctx context.Context, in *ListReviewReportsRequest, opts ...grpc.CallOption) (*ListReviewReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReviewReportsResponse)
	err := c.cc.Invoke(ctx, ReviewAdminService_ListReviewReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewAdminServiceClient) ResolveReviewDispute(ctx context.Context, in *ResolveReviewDisputeRequest, opts ...grpc.CallOption) (*ResolveReviewDisputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveReviewDisputeResponse)
	err := c.cc.Invoke(ctx, ReviewAdminService_ResolveReviewDispute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewAdminServiceClient) DeleteReview(ctx context.Context, in *DeleteReviewRequest, opts ...grpc.CallOption) (*DeleteReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReviewResponse)
	err := c.cc.Invoke(ctx, ReviewAdminService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewAdminServiceServer is the server API for ReviewAdminService service.
// All implementations must embed UnimplementedReviewAdminServiceServer
// for forward compatibility.
type ReviewAdminServiceServer interface {
	ListReviewDisputes(context.Context, *ListReviewDisputesRequest) (*ListReviewDisputesResponse, error)
	ListReviewReports(context.Context, *ListReviewReportsRequest) (*ListReviewReportsResponse, error)
	ResolveReviewDispute(context.Context, *ResolveReviewDisputeRequest) (*ResolveReviewDisputeResponse, error)
	DeleteReview(context.Context, *DeleteReviewRequest) (*DeleteReviewResponse, error)
	mustEmbedUnimplementedReviewAdminServiceServer()
}

// UnimplementedReviewAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewAdminServiceServer struct{}

func (UnimplementedReviewAdminServiceServer) ListReviewDisputes(context.Context, *ListReviewDisputesRequest) (*ListReviewDisputesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReviewDisputes not implemented")
}
func (UnimplementedReviewAdminServiceServer) ListReviewReports(context.Context, *ListReviewReportsRequest) (*ListReviewReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReviewReports not implemented")
}
func (UnimplementedReviewAdminServiceServer) ResolveReviewDispute(context.Context, *ResolveReviewDisputeRequest) (*ResolveReviewDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveReviewDispute not implemented")
}
func (UnimplementedReviewAdminServiceServer) DeleteReview(context.Context, *DeleteReviewRequest) (*DeleteReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedReviewAdminServiceServer) mustEmbedUnimplementedReviewAdminServiceServer() {}
func (UnimplementedReviewAdminServiceServer) testEmbeddedByValue()                            {}

// UnsafeReviewAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewAdminServiceServer will
// result in compilation errors.
type UnsafeReviewAdminServiceServer interface {
	mustEmbedUnimplementedReviewAdminServiceServer()
}

func RegisterReviewAdminServiceServer(s grpc.ServiceRegistrar, srv ReviewAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewAdminService_ServiceDesc, srv)
}

func _ReviewAdminService_ListReviewDisputes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewDisputesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewAdminServiceServer).ListReviewDisputes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewAdminService_ListReviewDisputes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewAdminServiceServer).ListReviewDisputes(ctx, req.(*ListReviewDisputesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewAdminService_ListReviewReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewAdminServiceServer).ListReviewReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewAdminService_ListReviewReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewAdminServiceServer).ListReviewReports(ctx, req.(*ListReviewReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewAdminService_ResolveReviewDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveReviewDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewAdminServiceServer).ResolveReviewDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewAdminService_ResolveReviewDispute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewAdminServiceServer).ResolveReviewDispute(ctx, req.(*ResolveReviewDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewAdminService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewAdminServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewAdminService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewAdminServiceServer).DeleteReview(ctx, req.(*DeleteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewAdminService_ServiceDesc is the grpc.ServiceDesc for ReviewAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "martketplace.vkr.review.v1.admin.ReviewAdminService",
	HandlerType: (*ReviewAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListReviewDisputes",
			Handler:    _ReviewAdminService_ListReviewDisputes_Handler,
		},
		{
			MethodName: "ListReviewReports",
			Handler:    _ReviewAdminService_ListReviewReports_Handler,
		},
		{
			MethodName: "ResolveReviewDispute",
			Handler:    _ReviewAdminService_ResolveReviewDispute_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _ReviewAdminService_DeleteReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin/review_admin_service.proto",
}
