// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/domain/review_domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	SortOrder     uint32                 `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewImage) Reset() {
	*x = ReviewImage{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewImage) ProtoMessage() {}

func (x *ReviewImage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewImage.ProtoReflect.Descriptor instead.
func (*ReviewImage) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewImage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReviewImage) GetSortOrder() uint32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewReply) Reset() {
	*x = ReviewReply{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewReply) ProtoMessage() {}

func (x *ReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewReply.ProtoReflect.Descriptor instead.
func (*ReviewReply) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewReply) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *ReviewReply) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReviewReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReviewDispute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AdminComment  string                 `protobuf:"bytes,5,opt,name=admin_comment,json=adminComment,proto3" json:"admin_comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewDispute) Reset() {
	*x = ReviewDispute{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDispute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDispute) ProtoMessage() {}

func (x *ReviewDispute) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDispute.ProtoReflect.Descriptor instead.
func (*ReviewDispute) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewDispute) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewDispute) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *ReviewDispute) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReviewDispute) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReviewDispute) GetAdminComment() string {
	if x != nil {
		return x.AdminComment
	}
	return ""
}

func (x *ReviewDispute) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReviewDispute) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

type Review struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId          int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VendorId           int64                  `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	AuthorUserId       int64                  `protobuf:"varint,4,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	AuthorName         string                 `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Rating             int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment            string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	ExcludedFromRating bool                   `protobuf:"varint,8,opt,name=excluded_from_rating,json=excludedFromRating,proto3" json:"excluded_from_rating,omitempty"`
	HelpfulCount       int64                  `protobuf:"varint,9,opt,name=helpful_count,json=helpfulCount,proto3" json:"helpful_count,omitempty"`
	NotHelpfulCount    int64                  `protobuf:"varint,10,opt,name=not_helpful_count,json=notHelpfulCount,proto3" json:"not_helpful_count,omitempty"`
	Images             []*ReviewImage         `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	Reply              *ReviewReply           `protobuf:"bytes,12,opt,name=reply,proto3" json:"reply,omitempty"`
	Dispute            *ReviewDispute         `protobuf:"bytes,13,opt,name=dispute,proto3" json:"dispute,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{3}
}

func (x *Review) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Review) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *Review) GetAuthorUserId() int64 {
	if x != nil {
		return x.AuthorUserId
	}
	return 0
}

func (x *Review) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetExcludedFromRating() bool {
	if x != nil {
		return x.ExcludedFromRating
	}
	return false
}

func (x *Review) GetHelpfulCount() int64 {
	if x != nil {
		return x.HelpfulCount
	}
	return 0
}

func (x *Review) GetNotHelpfulCount() int64 {
	if x != nil {
		return x.NotHelpfulCount
	}
	return 0
}

func (x *Review) GetImages() []*ReviewImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Review) GetReply() *ReviewReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *Review) GetDispute() *ReviewDispute {
	if x != nil {
		return x.Dispute
	}
	return nil
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Review) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RatingSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AverageRating  float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	RatingCount    int64                  `protobuf:"varint,3,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	OneStarCount   int64                  `protobuf:"varint,4,opt,name=one_star_count,json=oneStarCount,proto3" json:"one_star_count,omitempty"`
	TwoStarCount   int64                  `protobuf:"varint,5,opt,name=two_star_count,json=twoStarCount,proto3" json:"two_star_count,omitempty"`
	ThreeStarCount int64                  `protobuf:"varint,6,opt,name=three_star_count,json=threeStarCount,proto3" json:"three_star_count,omitempty"`
	FourStarCount  int64                  `protobuf:"varint,7,opt,name=four_star_count,json=fourStarCount,proto3" json:"four_star_count,omitempty"`
	FiveStarCount  int64                  `protobuf:"varint,8,opt,name=five_star_count,json=fiveStarCount,proto3" json:"five_star_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RatingSummary) Reset() {
	*x = RatingSummary{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingSummary) ProtoMessage() {}

func (x *RatingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingSummary.ProtoReflect.Descriptor instead.
func (*RatingSummary) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{4}
}

func (x *RatingSummary) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RatingSummary) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *RatingSummary) GetRatingCount() int64 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *RatingSummary) GetOneStarCount() int64 {
	if x != nil {
		return x.OneStarCount
	}
	return 0
}

func (x *RatingSummary) GetTwoStarCount() int64 {
	if x != nil {
		return x.TwoStarCount
	}
	return 0
}

func (x *RatingSummary) GetThreeStarCount() int64 {
	if x != nil {
		return x.ThreeStarCount
	}
	return 0
}

func (x *RatingSummary) GetFourStarCount() int64 {
	if x != nil {
		return x.FourStarCount
	}
	return 0
}

func (x *RatingSummary) GetFiveStarCount() int64 {
	if x != nil {
		return x.FiveStarCount
	}
	return 0
}

type ReviewReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReviewId       int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	ReporterUserId int64                  `protobuf:"varint,3,opt,name=reporter_user_id,json=reporterUserId,proto3" json:"reporter_user_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Details        string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReviewReport) Reset() {
	*x = ReviewReport{}
	mi := &file_v1_domain_review_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewReport) ProtoMessage() {}

func (x *ReviewReport) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_review_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewReport.ProtoReflect.Descriptor instead.
func (*ReviewReport) Descriptor() ([]byte, []int) {
	return file_v1_domain_review_domain_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewReport) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewReport) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReviewReport) GetReporterUserId() int64 {
	if x != nil {
		return x.ReporterUserId
	}
	return 0
}

func (x *ReviewReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReviewReport) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ReviewReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReviewReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_domain_review_domain_proto protoreflect.FileDescriptor

const file_v1_domain_review_domain_proto_rawDesc = "" +
	"\n" +
	"\x1dv1/domain/review_domain.proto\x12!martketplace.vkr.review.v1.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\vReviewImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\rR\tsortOrder\"\xca\x01\n" +
	"\vReviewReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x02\n" +
	"\rReviewDispute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\radmin_comment\x18\x05 \x01(\tR\fadminComment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vresolved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\"\xa0\x05\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\x03R\bvendorId\x12$\n" +
	"\x0eauthor_user_id\x18\x04 \x01(\x03R\fauthorUserId\x12\x1f\n" +
	"\vauthor_name\x18\x05 \x01(\tR\n" +
	"authorName\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x120\n" +
	"\x14excluded_from_rating\x18\b \x01(\bR\x12excludedFromRating\x12#\n" +
	"\rhelpful_count\x18\t \x01(\x03R\fhelpfulCount\x12*\n" +
	"\x11not_helpful_count\x18\n" +
	" \x01(\x03R\x0fnotHelpfulCount\x12F\n" +
	"\x06images\x18\v \x03(\v2..martketplace.vkr.review.v1.domain.ReviewImageR\x06images\x12D\n" +
	"\x05reply\x18\f \x01(\v2..martketplace.vkr.review.v1.domain.ReviewReplyR\x05reply\x12J\n" +
	"\adispute\x18\r \x01(\v20.martketplace.vkr.review.v1.domain.ReviewDisputeR\adispute\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x02\n" +
	"\rRatingSummary\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12!\n" +
	"\frating_count\x18\x03 \x01(\x03R\vratingCount\x12$\n" +
	"\x0eone_star_count\x18\x04 \x01(\x03R\foneStarCount\x12$\n" +
	"\x0etwo_star_count\x18\x05 \x01(\x03R\ftwoStarCount\x12(\n" +
	"\x10three_star_count\x18\x06 \x01(\x03R\x0ethreeStarCount\x12&\n" +
	"\x0ffour_star_count\x18\a \x01(\x03R\rfourStarCount\x12&\n" +
	"\x0ffive_star_count\x18\b \x01(\x03R\rfiveStarCount\"\xea\x01\n" +
	"\fReviewReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId\x12(\n" +
	"\x10reporter_user_id\x18\x03 \x01(\x03R\x0ereporterUserId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBBZ@github.com/martketplace-vkr/review/pkg/api/grpc/v1/domain;domainb\x06proto3"

var (
	file_v1_domain_review_domain_proto_rawDescOnce sync.Once
	file_v1_domain_review_domain_proto_rawDescData []byte
)

func file_v1_domain_review_domain_proto_rawDescGZIP() []byte {
	file_v1_domain_review_domain_proto_rawDescOnce.Do(func() {
		file_v1_domain_review_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_domain_review_domain_proto_rawDesc), len(file_v1_domain_review_domain_proto_rawDesc)))
	})
	return file_v1_domain_review_domain_proto_rawDescData
}

var file_v1_domain_review_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_domain_review_domain_proto_goTypes = []any{
	(*ReviewImage)(nil),           // 0: martketplace.vkr.review.v1.domain.ReviewImage
	(*ReviewReply)(nil),           // 1: martketplace.vkr.review.v1.domain.ReviewReply
	(*ReviewDispute)(nil),         // 2: martketplace.vkr.review.v1.domain.ReviewDispute
	(*Review)(nil),                // 3: martketplace.vkr.review.v1.domain.Review
	(*RatingSummary)(nil),         // 4: martketplace.vkr.review.v1.domain.RatingSummary
	(*ReviewReport)(nil),          // 5: martketplace.vkr.review.v1.domain.ReviewReport
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_v1_domain_review_domain_proto_depIdxs = []int32{
	6,  // 0: martketplace.vkr.review.v1.domain.ReviewReply.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: martketplace.vkr.review.v1.domain.ReviewReply.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: martketplace.vkr.review.v1.domain.ReviewDispute.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: martketplace.vkr.review.v1.domain.ReviewDispute.resolved_at:type_name -> google.protobuf.Timestamp
	0,  // 4: martketplace.vkr.review.v1.domain.Review.images:type_name -> martketplace.vkr.review.v1.domain.ReviewImage
	1,  // 5: martketplace.vkr.review.v1.domain.Review.reply:type_name -> martketplace.vkr.review.v1.domain.ReviewReply
	2,  // 6: martketplace.vkr.review.v1.domain.Review.dispute:type_name -> martketplace.vkr.review.v1.domain.ReviewDispute
	6,  // 7: martketplace.vkr.review.v1.domain.Review.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: martketplace.vkr.review.v1.domain.Review.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: martketplace.vkr.review.v1.domain.ReviewReport.created_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_domain_review_domain_proto_init() }
func file_v1_domain_review_domain_proto_init() {
	if File_v1_domain_review_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_domain_review_domain_proto_rawDesc), len(file_v1_domain_review_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_domain_review_domain_proto_goTypes,
		DependencyIndexes: file_v1_domain_review_domain_proto_depIdxs,
		MessageInfos:      file_v1_domain_review_domain_proto_msgTypes,
	}.Build()
	File_v1_domain_review_domain_proto = out.File
	file_v1_domain_review_domain_proto_goTypes = nil
	file_v1_domain_review_domain_proto_depIdxs = nil
}
