syntax = "proto3";

package martketplace.vkr.review.v1.admin;

option go_package = "github.com/martketplace-vkr/review/pkg/api/grpc/v1/admin;admin";

import "v1/domain/review_domain.proto";

service ReviewAdminService {
  rpc ListReviewDisputes(ListReviewDisputesRequest) returns (ListReviewDisputesResponse);
  rpc ListReviewReports(ListReviewReportsRequest) returns (ListReviewReportsResponse);
  rpc ResolveReviewDispute(ResolveReviewDisputeRequest) returns (ResolveReviewDisputeResponse);
  rpc DeleteReview(DeleteReviewRequest) returns (DeleteReviewResponse);
}

message ListReviewDisputesRequest {
  string status = 1;
}

message ListReviewDisputesResponse {
  repeated martketplace.vkr.review.v1.domain.Review reviews = 1;
}

message ListReviewReportsRequest {
  string status = 1;
}

message ReportedReview {
  martketplace.vkr.review.v1.domain.Review review = 1;
  martketplace.vkr.review.v1.domain.ReviewReport report = 2;
}

message ListReviewReportsResponse {
  repeated ReportedReview items = 1;
}

message ResolveReviewDisputeRequest {
  int64 admin_id = 1;
  int64 review_id = 2;
  int64 dispute_id = 3;
  string decision = 4;
  string comment = 5;
}

message ResolveReviewDisputeResponse {
  martketplace.vkr.review.v1.domain.Review review = 1;
}

message DeleteReviewRequest {
  int64 admin_id = 1;
  int64 review_id = 2;
}

message DeleteReviewResponse {
  bool deleted = 1;
}
