// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/client/review_client_service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReviewClientService_ListProductReviews_FullMethodName = "/martketplace.vkr.review.v1.client.ReviewClientService/ListProductReviews"
	ReviewClientService_CreateReview_FullMethodName       = "/martketplace.vkr.review.v1.client.ReviewClientService/CreateReview"
	ReviewClientService_VoteReview_FullMethodName         = "/martketplace.vkr.review.v1.client.ReviewClientService/VoteReview"
	ReviewClientService_ReportReview_FullMethodName       = "/martketplace.vkr.review.v1.client.ReviewClientService/ReportReview"
)

// ReviewClientServiceClient is the client API for ReviewClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewClientServiceClient interface {
	ListProductReviews(ctx context.Context, in *ListProductReviewsRequest, opts ...grpc.CallOption) (*ListProductReviewsResponse, error)
	CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error)
	VoteReview(ctx context.Context, in *VoteReviewRequest, opts ...grpc.CallOption) (*VoteReviewResponse, error)
	ReportReview(ctx context.Context, in *ReportReviewRequest, opts ...grpc.CallOption) (*ReportReviewResponse, error)
}

type reviewClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewClientServiceClient(cc grpc.ClientConnInterface) ReviewClientServiceClient {
	return &reviewClientServiceClient{cc}
}

func (c *reviewClientServiceClient) ListProductReviews(ctx context.Context, in *ListProductReviewsRequest, opts ...grpc.CallOption) (*ListProductReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductReviewsResponse)
	err := c.cc.Invoke(ctx, ReviewClientService_ListProductReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClientServiceClient) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...grpc.CallOption) (*CreateReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReviewResponse)
	err := c.cc.Invoke(ctx, ReviewClientService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClientServiceClient) VoteReview(ctx context.Context, in *VoteReviewRequest, opts ...grpc.CallOption) (*VoteReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteReviewResponse)
	err := c.cc.Invoke(ctx, ReviewClientService_VoteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClientServiceClient) ReportReview(ctx context.Context, in *ReportReviewRequest, opts ...grpc.CallOption) (*ReportReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportReviewResponse)
	err := c.cc.Invoke(ctx, ReviewClientService_ReportReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewClientServiceServer is the server API for ReviewClientService service.
// All implementations must embed UnimplementedReviewClientServiceServer
// for forward compatibility.
type ReviewClientServiceServer interface {
	ListProductReviews(context.Context, *ListProductReviewsRequest) (*ListProductReviewsResponse, error)
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	VoteReview(context.Context, *VoteReviewRequest) (*VoteReviewResponse, error)
	ReportReview(context.Context, *ReportReviewRequest) (*ReportReviewResponse, error)
	mustEmbedUnimplementedReviewClientServiceServer()
}

// UnimplementedReviewClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewClientServiceServer struct{}

func (UnimplementedReviewClientServiceServer) ListProductReviews(context.Context, *ListProductReviewsRequest) (*ListProductReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductReviews not implemented")
}
func (UnimplementedReviewClientServiceServer) CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedReviewClientServiceServer) VoteReview(context.Context, *VoteReviewRequest) (*VoteReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteReview not implemented")
}
func (UnimplementedReviewClientServiceServer) ReportReview(context.Context, *ReportReviewRequest) (*ReportReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportReview not implemented")
}
func (UnimplementedReviewClientServiceServer) mustEmbedUnimplementedReviewClientServiceServer() {}
func (UnimplementedReviewClientServiceServer) testEmbeddedByValue()                             {}

// UnsafeReviewClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewClientServiceServer will
// result in compilation errors.
type UnsafeReviewClientServiceServer interface {
	mustEmbedUnimplementedReviewClientServiceServer()
}

func RegisterReviewClientServiceServer(s grpc.ServiceRegistrar, srv ReviewClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewClientService_ServiceDesc, srv)
}

func _ReviewClientService_ListProductReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewClientServiceServer).ListProductReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewClientService_ListProductReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewClientServiceServer).ListProductReviews(ctx, req.(*ListProductReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewClientService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewClientServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewClientService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewClientServiceServer).CreateReview(ctx, req.(*CreateReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewClientService_VoteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewClientServiceServer).VoteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewClientService_VoteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewClientServiceServer).VoteReview(ctx, req.(*VoteReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewClientService_ReportReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewClientServiceServer).ReportReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewClientService_ReportReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewClientServiceServer).ReportReview(ctx, req.(*ReportReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewClientService_ServiceDesc is the grpc.ServiceDesc for ReviewClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "martketplace.vkr.review.v1.client.ReviewClientService",
	HandlerType: (*ReviewClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductReviews",
			Handler:    _ReviewClientService_ListProductReviews_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _ReviewClientService_CreateReview_Handler,
		},
		{
			MethodName: "VoteReview",
			Handler:    _ReviewClientService_VoteReview_Handler,
		},
		{
			MethodName: "ReportReview",
			Handler:    _ReviewClientService_ReportReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/client/review_client_service.proto",
}
