// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/review_client_service.proto

package client

import (
	domain "github.com/martketplace-vkr/review/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReviewsRequest) Reset() {
	*x = ListProductReviewsRequest{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReviewsRequest) ProtoMessage() {}

func (x *ListProductReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListProductReviewsRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductReviewsRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ListProductReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*domain.Review       `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Summary       *domain.RatingSummary  `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReviewsResponse) Reset() {
	*x = ListProductReviewsResponse{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReviewsResponse) ProtoMessage() {}

func (x *ListProductReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListProductReviewsResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductReviewsResponse) GetReviews() []*domain.Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListProductReviewsResponse) GetSummary() *domain.RatingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AuthorUserId  int64                  `protobuf:"varint,2,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	AuthorName    string                 `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,6,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReviewRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateReviewRequest) GetAuthorUserId() int64 {
	if x != nil {
		return x.AuthorUserId
	}
	return 0
}

func (x *CreateReviewRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *domain.Review         `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	Summary       *domain.RatingSummary  `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReviewResponse) GetReview() *domain.Review {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *CreateReviewResponse) GetSummary() *domain.RatingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type VoteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Vote          string                 `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteReviewRequest) Reset() {
	*x = VoteReviewRequest{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReviewRequest) ProtoMessage() {}

func (x *VoteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReviewRequest.ProtoReflect.Descriptor instead.
func (*VoteReviewRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *VoteReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *VoteReviewRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VoteReviewRequest) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

type VoteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *domain.Review         `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteReviewResponse) Reset() {
	*x = VoteReviewResponse{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReviewResponse) ProtoMessage() {}

func (x *VoteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReviewResponse.ProtoReflect.Descriptor instead.
func (*VoteReviewResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *VoteReviewResponse) GetReview() *domain.Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type ReportReviewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReviewId       int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	ReporterUserId int64                  `protobuf:"varint,2,opt,name=reporter_user_id,json=reporterUserId,proto3" json:"reporter_user_id,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Details        string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportReviewRequest) Reset() {
	*x = ReportReviewRequest{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReviewRequest) ProtoMessage() {}

func (x *ReportReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReviewRequest.ProtoReflect.Descriptor instead.
func (*ReportReviewRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReportReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReportReviewRequest) GetReporterUserId() int64 {
	if x != nil {
		return x.ReporterUserId
	}
	return 0
}

func (x *ReportReviewRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportReviewRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ReportReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *domain.ReviewReport   `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportReviewResponse) Reset() {
	*x = ReportReviewResponse{}
	mi := &file_v1_client_review_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportReviewResponse) ProtoMessage() {}

func (x *ReportReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_review_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportReviewResponse.ProtoReflect.Descriptor instead.
func (*ReportReviewResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_review_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *ReportReviewResponse) GetReport() *domain.ReviewReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_v1_client_review_client_service_proto protoreflect.FileDescriptor

const file_v1_client_review_client_service_proto_rawDesc = "" +
	"\n" +
	"%v1/client/review_client_service.proto\x12!martketplace.vkr.review.v1.client\x1a\x1dv1/domain/review_domain.proto\":\n" +
	"\x19ListProductReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"\xad\x01\n" +
	"\x1aListProductReviewsResponse\x12C\n" +
	"\areviews\x18\x01 \x03(\v2).martketplace.vkr.review.v1.domain.ReviewR\areviews\x12J\n" +
	"\asummary\x18\x02 \x01(\v20.martketplace.vkr.review.v1.domain.RatingSummaryR\asummary\"\xcc\x01\n" +
	"\x13CreateReviewRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12$\n" +
	"\x0eauthor_user_id\x18\x02 \x01(\x03R\fauthorUserId\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x06 \x03(\tR\timageUrls\"\xa5\x01\n" +
	"\x14CreateReviewResponse\x12A\n" +
	"\x06review\x18\x01 \x01(\v2).martketplace.vkr.review.v1.domain.ReviewR\x06review\x12J\n" +
	"\asummary\x18\x02 \x01(\v20.martketplace.vkr.review.v1.domain.RatingSummaryR\asummary\"]\n" +
	"\x11VoteReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\tR\x04vote\"W\n" +
	"\x12VoteReviewResponse\x12A\n" +
	"\x06review\x18\x01 \x01(\v2).martketplace.vkr.review.v1.domain.ReviewR\x06review\"\x8e\x01\n" +
	"\x13ReportReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12(\n" +
	"\x10reporter_user_id\x18\x02 \x01(\x03R\x0ereporterUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"_\n" +
	"\x14ReportReviewResponse\x12G\n" +
	"\x06report\x18\x01 \x01(\v2/.martketplace.vkr.review.v1.domain.ReviewReportR\x06report2\xa6\x04\n" +
	"\x13ReviewClientService\x12\x91\x01\n" +
	"\x12ListProductReviews\x12<.martketplace.vkr.review.v1.client.ListProductReviewsRequest\x1a=.martketplace.vkr.review.v1.client.ListProductReviewsResponse\x12\x7f\n" +
	"\fCreateReview\x126.martketplace.vkr.review.v1.client.CreateReviewRequest\x1a7.martketplace.vkr.review.v1.client.CreateReviewResponse\x12y\n" +
	"\n" +
	"VoteReview\x124.martketplace.vkr.review.v1.client.VoteReviewRequest\x1a5.martketplace.vkr.review.v1.client.VoteReviewResponse\x12\x7f\n" +
	"\fReportReview\x126.martketplace.vkr.review.v1.client.ReportReviewRequest\x1a7.martketplace.vkr.review.v1.client.ReportReviewResponseBBZ@github.com/martketplace-vkr/review/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_review_client_service_proto_rawDescOnce sync.Once
	file_v1_client_review_client_service_proto_rawDescData []byte
)

func file_v1_client_review_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_review_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_review_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_review_client_service_proto_rawDesc), len(file_v1_client_review_client_service_proto_rawDesc)))
	})
	return file_v1_client_review_client_service_proto_rawDescData
}

var file_v1_client_review_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_client_review_client_service_proto_goTypes = []any{
	(*ListProductReviewsRequest)(nil),  // 0: martketplace.vkr.review.v1.client.ListProductReviewsRequest
	(*ListProductReviewsResponse)(nil), // 1: martketplace.vkr.review.v1.client.ListProductReviewsResponse
	(*CreateReviewRequest)(nil),        // 2: martketplace.vkr.review.v1.client.CreateReviewRequest
	(*CreateReviewResponse)(nil),       // 3: martketplace.vkr.review.v1.client.CreateReviewResponse
	(*VoteReviewRequest)(nil),          // 4: martketplace.vkr.review.v1.client.VoteReviewRequest
	(*VoteReviewResponse)(nil),         // 5: martketplace.vkr.review.v1.client.VoteReviewResponse
	(*ReportReviewRequest)(nil),        // 6: martketplace.vkr.review.v1.client.ReportReviewRequest
	(*ReportReviewResponse)(nil),       // 7: martketplace.vkr.review.v1.client.ReportReviewResponse
	(*domain.Review)(nil),              // 8: martketplace.vkr.review.v1.domain.Review
	(*domain.RatingSummary)(nil),       // 9: martketplace.vkr.review.v1.domain.RatingSummary
	(*domain.ReviewReport)(nil),        // 10: martketplace.vkr.review.v1.domain.ReviewReport
}
var file_v1_client_review_client_service_proto_depIdxs = []int32{
	8,  // 0: martketplace.vkr.review.v1.client.ListProductReviewsResponse.reviews:type_name -> martketplace.vkr.review.v1.domain.Review
	9,  // 1: martketplace.vkr.review.v1.client.ListProductReviewsResponse.summary:type_name -> martketplace.vkr.review.v1.domain.RatingSummary
	8,  // 2: martketplace.vkr.review.v1.client.CreateReviewResponse.review:type_name -> martketplace.vkr.review.v1.domain.Review
	9,  // 3: martketplace.vkr.review.v1.client.CreateReviewResponse.summary:type_name -> martketplace.vkr.review.v1.domain.RatingSummary
	8,  // 4: martketplace.vkr.review.v1.client.VoteReviewResponse.review:type_name -> martketplace.vkr.review.v1.domain.Review
	10, // 5: martketplace.vkr.review.v1.client.ReportReviewResponse.report:type_name -> martketplace.vkr.review.v1.domain.ReviewReport
	0,  // 6: martketplace.vkr.review.v1.client.ReviewClientService.ListProductReviews:input_type -> martketplace.vkr.review.v1.client.ListProductReviewsRequest
	2,  // 7: martketplace.vkr.review.v1.client.ReviewClientService.CreateReview:input_type -> martketplace.vkr.review.v1.client.CreateReviewRequest
	4,  // 8: martketplace.vkr.review.v1.client.ReviewClientService.VoteReview:input_type -> martketplace.vkr.review.v1.client.VoteReviewRequest
	6,  // 9: martketplace.vkr.review.v1.client.ReviewClientService.ReportReview:input_type -> martketplace.vkr.review.v1.client.ReportReviewRequest
	1,  // 10: martketplace.vkr.review.v1.client.ReviewClientService.ListProductReviews:output_type -> martketplace.vkr.review.v1.client.ListProductReviewsResponse
	3,  // 11: martketplace.vkr.review.v1.client.ReviewClientService.CreateReview:output_type -> martketplace.vkr.review.v1.client.CreateReviewResponse
	5,  // 12: martketplace.vkr.review.v1.client.ReviewClientService.VoteReview:output_type -> martketplace.vkr.review.v1.client.VoteReviewResponse
	7,  // 13: martketplace.vkr.review.v1.client.ReviewClientService.ReportReview:output_type -> martketplace.vkr.review.v1.client.ReportReviewResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_client_review_client_service_proto_init() }
func file_v1_client_review_client_service_proto_init() {
	if File_v1_client_review_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_review_client_service_proto_rawDesc), len(file_v1_client_review_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_review_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_review_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_review_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_review_client_service_proto = out.File
	file_v1_client_review_client_service_proto_goTypes = nil
	file_v1_client_review_client_service_proto_depIdxs = nil
}
